# Forest Green

palette = 0=#213230
palette = 1=#b97872
palette = 2=#5a8e73
palette = 3=#b9a66c
palette = 4=#6f9a91
palette = 5=#43725d
palette = 6=#6f9a91
palette = 7=#dce8e1
palette = 8=#43725d
palette = 9=#b97872
palette = 10=#5a8e73
palette = 11=#b9a66c
palette = 12=#6f9a91
palette = 13=#5a8e73
palette = 14=#6f9a91
palette = 15=#f3f7f5
palette = 16=#b9a66c
palette = 17=#b97872

background = #192324
foreground = #dce8e1
cursor-color = #5a8e73
cursor-text = #192324
selection-background = #345b4b
selection-foreground = #f3f7f5
