#!/bin/bash 

DEFAULT_SESSION=dwm

if [ $DEFAULT_SESSION = dwm ]; then
	sleep 5 && ~/.scripts/dwm_status.sh &
	sleep 5 && steam &
	# sleep 5 && lutris &
	sleep 6 && st &
	sleep 5 && thunderbird &
	sleep 5 && redshift &
	sleep 5 && firefox &
	sleep 5 && variety &
	sleep 5 && numlockx &
	sleep 5 && unclutter &
	sleep 4 && compton &
fi

exec dwm

#while true; do
#	# Log stderror to a file 
#	dwm 2> ~/.dwm.log
#	# No error logging
#	#dwm >/dev/null 2>&1
#done
