[main]
font=Monaspace Neon NF:size=14
include=/home/rathel/.config/fuzzel/themes/forest-green.ini
dpi-aware=auto

# Fuzzel uses character/row units rather than percentages.
anchor=left
width=41
lines=100

[border]
radius=0
