#!/usr/bin/sh

wal -i ~/Syncthing/Backgrounds &

redshift &
sxhkd &
polybar example &
compton &
dunst &
seapplet &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config split_ratio          0.70
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#00ff00"
bspc config focus_follows_pointer true 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^2'
