# Forest Green
[colors]
background=192324ff
text=dce8e1ff
prompt=f3f7f5ff
placeholder=a9beb3ff
input=dce8e1ff
match=6f9a91ff
selection=345b4bff
selection-text=f3f7f5ff
selection-match=6f9a91ff
counter=a9beb3ff
border=5a8e73ff
