# TokyoNight Night
[colors]
background=1a1b26ff
text=c0caf5ff
prompt=e0e6ffff
placeholder=565f89ff
input=c0caf5ff
match=7dcfffff
selection=33467cff
selection-text=e0e6ffff
selection-match=7aa2f7ff
counter=565f89ff
border=7aa2f7ff
