set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -sg extended-keys on
set -sg extended-keys-format csi-u

# TokyoNight Night
set -g status-style "bg=#1a1b26,fg=#c0caf5"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#7aa2f7,fg=#1a1b26,bold] #S #[default]"
set -g status-right "#[fg=#7dcfff]%Y-%m-%d #[fg=#7aa2f7,bold]%H:%M "
set -g window-status-format "#[bg=#1a1b26,fg=#414868] #I:#W "
set -g window-status-current-format "#[bg=#24283b,fg=#c0caf5,bold] #I:#W "
set -g window-status-bell-style "bg=#f7768e,fg=#e0e6ff,bold"
set -g pane-border-style "fg=#16161e"
set -g pane-active-border-style "fg=#7aa2f7"
set -g message-style "bg=#24283b,fg=#c0caf5"
set -g message-command-style "bg=#24283b,fg=#7aa2f7"
set -g mode-style "bg=#33467c,fg=#e0e6ff"
set -g clock-mode-colour "#7aa2f7"
