[Appearance]
color_scheme_path=/home/rathel/.config/qt6ct/colors/nord-polar-night.conf
custom_palette=true
icon_theme=Nord-Breeze
style=Fusion

[Fonts]
fixed="Monaspace Neon NF,10,-1,5,400,0,0,0,0,0,0,0,0,0,1"
general="Monaspace Neon NF,10,-1,5,400,0,0,0,0,0,0,0,0,0,1"
