# Fish completions for pi, the AI coding agent.

# Subcommands.
complete -c pi -n '__fish_use_subcommand' -f -a 'install' -d 'Install an extension or package'
complete -c pi -n '__fish_use_subcommand' -f -a 'remove' -d 'Remove an installed extension or package'
complete -c pi -n '__fish_use_subcommand' -f -a 'uninstall' -d 'Alias for remove'
complete -c pi -n '__fish_use_subcommand' -f -a 'update' -d 'Update extensions, pi, or model catalogs'
complete -c pi -n '__fish_use_subcommand' -f -a 'list' -d 'List installed extensions'
complete -c pi -n '__fish_use_subcommand' -f -a 'config' -d 'Configure package resources'

# General options.
complete -c pi -s h -l help -f -d 'Show help'
complete -c pi -s v -l version -f -d 'Show version number'
complete -c pi -l provider -r -d 'Provider name'
complete -c pi -l model -r -d 'Model pattern or ID'
complete -c pi -l api-key -r -d 'API key'
complete -c pi -l system-prompt -r -d 'System prompt'
complete -c pi -l append-system-prompt -r -d 'Append text or file contents to the system prompt'
complete -c pi -l mode -r -a 'text json rpc' -d 'Output mode'
complete -c pi -s c -l continue -f -d 'Continue the previous session'
complete -c pi -s r -l resume -f -d 'Select a session to resume'
complete -c pi -l session -r -d 'Use a session file or partial UUID'
complete -c pi -l session-id -r -d 'Use an exact session ID'
complete -c pi -l fork -r -d 'Fork a session'
complete -c pi -l session-dir -r -a '(__fish_complete_directories)' -d 'Session storage directory'
complete -c pi -s n -l name -r -d 'Set the session display name'
complete -c pi -l models -r -d 'Models to cycle through (comma-separated)'
complete -c pi -s nbt -l no-builtin-tools -f -d 'Disable built-in tools'
complete -c pi -s nt -l no-tools -f -d 'Disable all tools by default'
complete -c pi -s t -l tools -r -d 'Comma-separated tool allowlist'
complete -c pi -s xt -l exclude-tools -r -d 'Comma-separated tool denylist'
complete -c pi -l thinking -r -a 'off minimal low medium high xhigh max' -d 'Thinking level'
complete -c pi -s e -l extension -r -a '(__fish_complete_path)' -d 'Load an extension file'
complete -c pi -l no-extensions -f -d 'Disable extension discovery'
complete -c pi -l skill -r -a '(__fish_complete_path)' -d 'Load a skill file or directory'
complete -c pi -l no-skills -f -d 'Disable skills discovery'
complete -c pi -l prompt-template -r -a '(__fish_complete_path)' -d 'Load a prompt template'
complete -c pi -l no-prompt-templates -f -d 'Disable prompt template discovery'
complete -c pi -l theme -r -a '(__fish_complete_path)' -d 'Load a theme'
complete -c pi -l no-themes -f -d 'Disable theme discovery'
complete -c pi -l no-context-files -f -d 'Disable AGENTS.md and CLAUDE.md discovery'
complete -c pi -l export -r -a '(__fish_complete_path)' -d 'Export a session to HTML'
complete -c pi -l list-models -f -d 'List available models'
complete -c pi -l verbose -f -d 'Force verbose startup'
complete -c pi -s a -l approve -f -d 'Trust project-local files'
complete -c pi -s na -l no-approve -f -d 'Ignore project-local files'
complete -c pi -l offline -f -d 'Disable startup network operations'

# Subcommand options and arguments.
complete -c pi -n '__fish_seen_subcommand_from install' -s l -l local -f -d 'Install at local/project scope'
complete -c pi -n '__fish_seen_subcommand_from install' -a '(__fish_complete_path)' -d 'Extension or package source'
complete -c pi -n '__fish_seen_subcommand_from remove uninstall' -s l -l local -f -d 'Remove from local/project scope'
complete -c pi -n '__fish_seen_subcommand_from remove uninstall' -a '(__fish_complete_path)' -d 'Extension or package source'
complete -c pi -n '__fish_seen_subcommand_from update' -a 'self pi' -d 'Update target'
complete -c pi -n '__fish_seen_subcommand_from update' -a '(__fish_complete_path)' -d 'Extension source'
