# ~/.config/alacritty/alacritty.toml

[general]
import = ["catppuccin-mocha.toml"] 

[window]
opacity = 0.9
decorations = "full"

[window.padding]
x = 0
y = 0

[font]
size = 14.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"
